name: Publish package to GitHub Packages
on:
  push:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@torx-software'
      - run: ls -la
      - run: ln -s $NPM_CONFIG_USERCONFIG .npmrc
      - run: cat .npmrc
      - run: npm config set loglevel verbose
      - run: npm install
      - run: npm ci
      - run: npm publish --loglevel verbose --scope=@torx-software
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}